#! /bin/sh

#Autostart
sxhkd &
picom -b --experimental-backends --config ~/.config/picom/picom.conf
polybar example &

#Monitors
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Rhythmbox destop='4' focus=on 
bspc rule -a Firefox desktop='^2' focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
